module.exports = {
  ProfileModel: require('./lib/ProfileModel').model,
  ProfileWorkerModel: require('./lib/ProfileWorkerModel').model,
  ProfileRecruiterModel: require('./lib/ProfileRecruiterModel').model,
  ProfileClientModel: require('./lib/ProfileClientModel').model,
  WorkerServiceModel: require('./lib/WorkerServiceModel').model,
  WorkerSocialModel: require('./lib/WorkerSocialModel').model,
  WorkerEmploymentModel: require('./lib/WorkerEmploymentModel').model,
  RecruiterServiceModel: require('./lib/RecruiterServiceModel').model,
  RecruiterSocialModel: require('./lib/RecruiterSocialModel').model,
  ClientCollaboratorModel: require('./lib/ClientCollaboratorModel').model,
  PersonModel: require('./lib/PersonModel').model,
  AgentModel: require('./lib/AgentModel').model,
  VerificationRequestLevel1Model: require('./lib/VerificationRequestLevel1Model').model,
  VerificationRequestLevel2Model: require('./lib/VerificationRequestLevel2Model').model,
  VerificationRequestLevel3Model: require('./lib/VerificationRequestLevel3Model').model,
  VerificationRequestLevel4Model: require('./lib/VerificationRequestLevel4Model').model,
  VerificationRequestWorkerModel: require('./lib/VerificationRequestWorkerModel').model,
  VerificationRequestRecruiterModel: require('./lib/VerificationRequestRecruiterModel').model,
  VerificationRequestClientModel: require('./lib/VerificationRequestClientModel').model,
  ConfirmationRequestLevel2Model: require('./lib/ConfirmationRequestLevel2Model').model,
  NotificationToggleModel: require('./lib/NotificationToggleModel').model,
  CreateAgentModel: require('./lib/CreateAgentModel').model
}
